// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DatabaseLicenseType.
const (
	Evaluation   DatabaseLicenseType = "evaluation"
	LessThanNil  DatabaseLicenseType = "<nil>"
	Redistribute DatabaseLicenseType = "redistribute"
	Standard     DatabaseLicenseType = "standard"
)

// Valid indicates whether the value is a known member of the DatabaseLicenseType enum.
func (e DatabaseLicenseType) Valid() bool {
	switch e {
	case Evaluation:
		return true
	case LessThanNil:
		return true
	case Redistribute:
		return true
	case Standard:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStanding.
const (
	DatabaseStandingExpired    DatabaseStanding = "expired"
	DatabaseStandingLicensed   DatabaseStanding = "licensed"
	DatabaseStandingUnlicensed DatabaseStanding = "unlicensed"
)

// Valid indicates whether the value is a known member of the DatabaseStanding enum.
func (e DatabaseStanding) Valid() bool {
	switch e {
	case DatabaseStandingExpired:
		return true
	case DatabaseStandingLicensed:
		return true
	case DatabaseStandingUnlicensed:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseVersionFormats.
const (
	DatabaseVersionFormatsCsvgz DatabaseVersionFormats = "csvgz"
	DatabaseVersionFormatsMmdb  DatabaseVersionFormats = "mmdb"
)

// Valid indicates whether the value is a known member of the DatabaseVersionFormats enum.
func (e DatabaseVersionFormats) Valid() bool {
	switch e {
	case DatabaseVersionFormatsCsvgz:
		return true
	case DatabaseVersionFormatsMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DownloadOutcome.
const (
	DownloadOutcomeDenied       DownloadOutcome = "denied"
	DownloadOutcomeExpired      DownloadOutcome = "expired"
	DownloadOutcomeOk           DownloadOutcome = "ok"
	DownloadOutcomeUnauthorized DownloadOutcome = "unauthorized"
	DownloadOutcomeUnavailable  DownloadOutcome = "unavailable"
	DownloadOutcomeUnknown      DownloadOutcome = "unknown"
)

// Valid indicates whether the value is a known member of the DownloadOutcome enum.
func (e DownloadOutcome) Valid() bool {
	switch e {
	case DownloadOutcomeDenied:
		return true
	case DownloadOutcomeExpired:
		return true
	case DownloadOutcomeOk:
		return true
	case DownloadOutcomeUnauthorized:
		return true
	case DownloadOutcomeUnavailable:
		return true
	case DownloadOutcomeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for DBFormat.
const (
	DBFormatCsvgz DBFormat = "csvgz"
	DBFormatMmdb  DBFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DBFormat enum.
func (e DBFormat) Valid() bool {
	switch e {
	case DBFormatCsvgz:
		return true
	case DBFormatMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseChecksumV2ParamsFormat.
const (
	DatabaseChecksumV2ParamsFormatCsvgz DatabaseChecksumV2ParamsFormat = "csvgz"
	DatabaseChecksumV2ParamsFormatMmdb  DatabaseChecksumV2ParamsFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DatabaseChecksumV2ParamsFormat enum.
func (e DatabaseChecksumV2ParamsFormat) Valid() bool {
	switch e {
	case DatabaseChecksumV2ParamsFormatCsvgz:
		return true
	case DatabaseChecksumV2ParamsFormatMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseChecksumV2200JSONResponseBodyFormat.
const (
	DatabaseChecksumV2200JSONResponseBodyFormatCsvgz DatabaseChecksumV2200JSONResponseBodyFormat = "csvgz"
	DatabaseChecksumV2200JSONResponseBodyFormatMmdb  DatabaseChecksumV2200JSONResponseBodyFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DatabaseChecksumV2200JSONResponseBodyFormat enum.
func (e DatabaseChecksumV2200JSONResponseBodyFormat) Valid() bool {
	switch e {
	case DatabaseChecksumV2200JSONResponseBodyFormatCsvgz:
		return true
	case DatabaseChecksumV2200JSONResponseBodyFormatMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DownloadDatabaseV2ParamsFormat.
const (
	DownloadDatabaseV2ParamsFormatCsvgz DownloadDatabaseV2ParamsFormat = "csvgz"
	DownloadDatabaseV2ParamsFormatMmdb  DownloadDatabaseV2ParamsFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DownloadDatabaseV2ParamsFormat enum.
func (e DownloadDatabaseV2ParamsFormat) Valid() bool {
	switch e {
	case DownloadDatabaseV2ParamsFormatCsvgz:
		return true
	case DownloadDatabaseV2ParamsFormatMmdb:
		return true
	default:
		return false
	}
}

// Database One database FAMILY, with your organization's licence beside it. A
// licence covers the family, while a download names a specific version,
// so the ids passed to `download` and `checksum` come from `versions`.
type Database struct {
	// Base The family, e.g. `vpn_ip`. What a licence is held against.
	//
	// Example: vpn_ip
	Base string `json:"base"`

	// Expires Null when the licence has no end date, or when there is none.
	Expires *time.Time `json:"expires"`

	// LicenseType What your licence permits you to do with the data. Null when there
	// is no licence.
	LicenseType *DatabaseLicenseType `json:"license_type"`

	// Name Example: VPN IP
	Name string `json:"name"`

	// Standing `licensed` is a live grant, `expired` one whose term has ended, and
	// `unlicensed` a database published but never bought.
	Standing DatabaseStanding `json:"standing"`
	Starts   *time.Time       `json:"starts"`

	// Summary One line on what the newest version contains.
	Summary string `json:"summary"`

	// Versions Every published version of this family, oldest first. Old versions
	// are frozen rather than migrated, so both stay downloadable.
	Versions []DatabaseVersion `json:"versions"`
}

// DatabaseLicenseType What your licence permits you to do with the data. Null when there
// is no licence.
type DatabaseLicenseType string

// DatabaseStanding `licensed` is a live grant, `expired` one whose term has ended, and
// `unlicensed` a database published but never bought.
type DatabaseStanding string

// DatabaseMetadata The build document written by the exporter, served through unchanged.
type DatabaseMetadata struct {
	// Entries Row count in the current build.
	Entries int64  `json:"entries"`
	ID      string `json:"id"`

	// Sample A few real rows, keyed by format.
	Sample *map[string][]map[string]interface{} `json:"sample,omitempty"`

	// Schema Columns, keyed by format.
	Schema map[string][]DatabaseMetadataColumn `json:"schema"`

	// Size Bytes per format.
	Size map[string]int64 `json:"size"`

	// UpdateFreq How often a new build is published.
	UpdateFreq *string `json:"update_freq,omitempty"`

	// Updated ISO-8601 date (YYYY-MM-DD) the published build was generated on.
	//
	// Example: 2026-09-04
	Updated openapi_types.Date `json:"updated"`
}

// DatabaseMetadataColumn defines model for DatabaseMetadataColumn.
type DatabaseMetadataColumn struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
}

// DatabaseVersion defines model for DatabaseVersion.
type DatabaseVersion struct {
	// Formats The formats this version is BUILT in. Asking for another is a 400,
	// not a gap - the `_provider` catalogs are keyed by provider id, so no
	// MMDB exists for them.
	Formats []DatabaseVersionFormats `json:"formats"`

	// ID The versioned id. Pass this to `download`, `checksum` and `metadata`.
	//
	// Example: vpn_ip_v1
	ID      string `json:"id"`
	Summary string `json:"summary"`

	// Version Example: 1
	Version int `json:"version"`
}

// DatabaseVersionFormats defines model for DatabaseVersion.Formats.
type DatabaseVersionFormats string

// DBChecksums defines model for DbChecksums.
type DBChecksums struct {
	// Md5 Hex-encoded MD5 digest.
	Md5 string `json:"md5"`

	// Sha1 Hex-encoded SHA-1 digest.
	Sha1 string `json:"sha1"`

	// Sha256 Hex-encoded SHA-256 digest.
	Sha256 string `json:"sha256"`

	// Sha512 Hex-encoded SHA-512 digest.
	Sha512 string `json:"sha512"`
}

// Download One download ATTEMPT, refusals included.
type Download struct {
	// ApikeyID The key that made the request. Null when it could not be resolved.
	ApikeyID *string `json:"apikey_id"`

	// Bytes Object size at redirect time, NOT bytes delivered: the transfer is a
	// presigned redirect straight to object storage, so we never observe
	// how much of it was taken.
	Bytes      *int64          `json:"bytes"`
	ClientIP   *string         `json:"client_ip"`
	Created    time.Time       `json:"created"`
	DatasetID  string          `json:"dataset_id"`
	Format     string          `json:"format"`
	HTTPStatus *int            `json:"http_status"`
	Outcome    DownloadOutcome `json:"outcome"`
	UserAgent  *string         `json:"user_agent"`
}

// DownloadOutcome defines model for Download.Outcome.
type DownloadOutcome string

// Error defines model for Error.
type Error struct {
	// Rc A machine-readable result code. Deliberately not an enum: a code
	// added later must stay parseable by a client generated today.
	Rc string `json:"rc"`
}

// DBFormat Example: mmdb
type DBFormat string

// DBID Example: vpn_ip_v1
type DBID = string

// V2NotAvailable defines model for V2NotAvailable.
type V2NotAvailable = Error

// V2NotLicensed defines model for V2NotLicensed.
type V2NotLicensed = Error

// V2Unauthorized defines model for V2Unauthorized.
type V2Unauthorized = Error

// V2UnknownDatabase defines model for V2UnknownDatabase.
type V2UnknownDatabase = Error

// DatabaseChecksumV2Params defines parameters for DatabaseChecksumV2.
type DatabaseChecksumV2Params struct {
	// ID Database identifier (e.g. `vpn_ip_v1`, `resproxy_provider_v1`).
	ID DBID `form:"id" json:"id"`

	// Format Database file format.
	Format DatabaseChecksumV2ParamsFormat `form:"format" json:"format"`
}

// DatabaseChecksumV2ParamsFormat defines parameters for DatabaseChecksumV2.
type DatabaseChecksumV2ParamsFormat string

// DatabaseChecksumV2200JSONResponseBodyFormat defines parameters for DatabaseChecksumV2.
type DatabaseChecksumV2200JSONResponseBodyFormat string

// DownloadDatabaseV2Params defines parameters for DownloadDatabaseV2.
type DownloadDatabaseV2Params struct {
	// ID Database identifier (e.g. `vpn_ip_v1`, `resproxy_provider_v1`).
	ID DBID `form:"id" json:"id"`

	// Format Database file format.
	Format DownloadDatabaseV2ParamsFormat `form:"format" json:"format"`
}

// DownloadDatabaseV2ParamsFormat defines parameters for DownloadDatabaseV2.
type DownloadDatabaseV2ParamsFormat string

// ListDownloadsParams defines parameters for ListDownloads.
type ListDownloadsParams struct {
	// Limit How many attempts to return. Clamped to 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DatabaseMetadataV2Params defines parameters for DatabaseMetadataV2.
type DatabaseMetadataV2Params struct {
	// ID Database identifier (e.g. `vpn_ip_v1`, `resproxy_provider_v1`).
	ID DBID `form:"id" json:"id"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// DatabaseChecksumV2 Checksums
	//
	// Checksums for one published file, so a download can be verified after it lands.
	//
	// Corresponds with GET /api/v2/database/checksum (the `DatabaseChecksumV2` operationId).
	DatabaseChecksumV2(ctx context.Context, params *DatabaseChecksumV2Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadDatabaseV2 Download
	//
	// Answers `302`; the bytes come straight from object storage rather than
	// through this API. Follow the redirect.
	//
	// Corresponds with GET /api/v2/database/download (the `DownloadDatabaseV2` operationId).
	DownloadDatabaseV2(ctx context.Context, params *DownloadDatabaseV2Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDownloads History
	//
	// Refusals are listed too: a denial is what answers "it stopped working",
	// and its absence answers nothing.
	//
	// Corresponds with GET /api/v2/database/downloads (the `ListDownloads` operationId).
	ListDownloads(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDatabases List
	//
	// The whole published catalog, with your organization's licence beside
	// each entry, so `standing` says whether a database is yours today
	// (`licensed`), was (`expired`), or has never been bought (`unlicensed`).
	//
	// Corresponds with GET /api/v2/database/list (the `ListDatabases` operationId).
	ListDatabases(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatabaseMetadataV2 Metadata
	//
	// Poll this to decide whether today's build is worth fetching: it carries
	// `updated` and `entries` without downloading anything.
	//
	// No `format` parameter - one document describes every format the database
	// is built in.
	//
	// Corresponds with GET /api/v2/database/metadata (the `DatabaseMetadataV2` operationId).
	DatabaseMetadataV2(ctx context.Context, params *DatabaseMetadataV2Params, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// DatabaseChecksumV2 Checksums
//
// Checksums for one published file, so a download can be verified after it lands.
//
// Corresponds with GET /api/v2/database/checksum (the `DatabaseChecksumV2` operationId).
func (c *Client) DatabaseChecksumV2(ctx context.Context, params *DatabaseChecksumV2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatabaseChecksumV2Request(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DownloadDatabaseV2 Download
//
// Answers `302`; the bytes come straight from object storage rather than
// through this API. Follow the redirect.
//
// Corresponds with GET /api/v2/database/download (the `DownloadDatabaseV2` operationId).
func (c *Client) DownloadDatabaseV2(ctx context.Context, params *DownloadDatabaseV2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadDatabaseV2Request(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListDownloads History
//
// Refusals are listed too: a denial is what answers "it stopped working",
// and its absence answers nothing.
//
// Corresponds with GET /api/v2/database/downloads (the `ListDownloads` operationId).
func (c *Client) ListDownloads(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDownloadsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListDatabases List
//
// The whole published catalog, with your organization's licence beside
// each entry, so `standing` says whether a database is yours today
// (`licensed`), was (`expired`), or has never been bought (`unlicensed`).
//
// Corresponds with GET /api/v2/database/list (the `ListDatabases` operationId).
func (c *Client) ListDatabases(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDatabasesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DatabaseMetadataV2 Metadata
//
// Poll this to decide whether today's build is worth fetching: it carries
// `updated` and `entries` without downloading anything.
//
// No `format` parameter - one document describes every format the database
// is built in.
//
// Corresponds with GET /api/v2/database/metadata (the `DatabaseMetadataV2` operationId).
func (c *Client) DatabaseMetadataV2(ctx context.Context, params *DatabaseMetadataV2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatabaseMetadataV2Request(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDatabaseChecksumV2Request constructs an http.Request for the DatabaseChecksumV2 method
func NewDatabaseChecksumV2Request(server string, params *DatabaseChecksumV2Params) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/database/checksum")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", params.ID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownloadDatabaseV2Request constructs an http.Request for the DownloadDatabaseV2 method
func NewDownloadDatabaseV2Request(server string, params *DownloadDatabaseV2Params) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/database/download")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", params.ID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDownloadsRequest constructs an http.Request for the ListDownloads method
func NewListDownloadsRequest(server string, params *ListDownloadsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/database/downloads")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDatabasesRequest constructs an http.Request for the ListDatabases method
func NewListDatabasesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/database/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatabaseMetadataV2Request constructs an http.Request for the DatabaseMetadataV2 method
func NewDatabaseMetadataV2Request(server string, params *DatabaseMetadataV2Params) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/database/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", params.ID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// DatabaseChecksumV2WithResponse Checksums
	//
	// Checksums for one published file, so a download can be verified after it lands.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v2/database/checksum (the `DatabaseChecksumV2` operationId).
	DatabaseChecksumV2WithResponse(ctx context.Context, params *DatabaseChecksumV2Params, reqEditors ...RequestEditorFn) (*DatabaseChecksumV2Response, error)

	// DownloadDatabaseV2WithResponse Download
	//
	// Answers `302`; the bytes come straight from object storage rather than
	// through this API. Follow the redirect.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v2/database/download (the `DownloadDatabaseV2` operationId).
	DownloadDatabaseV2WithResponse(ctx context.Context, params *DownloadDatabaseV2Params, reqEditors ...RequestEditorFn) (*DownloadDatabaseV2Response, error)

	// ListDownloadsWithResponse History
	//
	// Refusals are listed too: a denial is what answers "it stopped working",
	// and its absence answers nothing.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v2/database/downloads (the `ListDownloads` operationId).
	ListDownloadsWithResponse(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*ListDownloadsResponse, error)

	// ListDatabasesWithResponse List
	//
	// The whole published catalog, with your organization's licence beside
	// each entry, so `standing` says whether a database is yours today
	// (`licensed`), was (`expired`), or has never been bought (`unlicensed`).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v2/database/list (the `ListDatabases` operationId).
	ListDatabasesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDatabasesResponse, error)

	// DatabaseMetadataV2WithResponse Metadata
	//
	// Poll this to decide whether today's build is worth fetching: it carries
	// `updated` and `entries` without downloading anything.
	//
	// No `format` parameter - one document describes every format the database
	// is built in.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v2/database/metadata (the `DatabaseMetadataV2` operationId).
	DatabaseMetadataV2WithResponse(ctx context.Context, params *DatabaseMetadataV2Params, reqEditors ...RequestEditorFn) (*DatabaseMetadataV2Response, error)
}

type DatabaseChecksumV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Checksums DBChecksums                                 `json:"checksums"`
		Format    DatabaseChecksumV2200JSONResponseBodyFormat `json:"format"`
		ID        string                                      `json:"id"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *V2Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *V2NotLicensed
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *V2UnknownDatabase
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *V2NotAvailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DatabaseChecksumV2Response) GetJSON200() *struct {
	Checksums DBChecksums                                 `json:"checksums"`
	Format    DatabaseChecksumV2200JSONResponseBodyFormat `json:"format"`
	ID        string                                      `json:"id"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DatabaseChecksumV2Response) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DatabaseChecksumV2Response) GetJSON401() *V2Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DatabaseChecksumV2Response) GetJSON403() *V2NotLicensed {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DatabaseChecksumV2Response) GetJSON404() *V2UnknownDatabase {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DatabaseChecksumV2Response) GetJSON503() *V2NotAvailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DatabaseChecksumV2Response) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DatabaseChecksumV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatabaseChecksumV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatabaseChecksumV2Response) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DownloadDatabaseV2Response302Headers the declared response headers of an HTTP 302 response for DownloadDatabaseV2
type DownloadDatabaseV2Response302Headers struct {
	Location *string
}

type DownloadDatabaseV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *V2Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *V2NotLicensed
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *V2UnknownDatabase
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *V2NotAvailable
	// Headers302 the parsed response headers for an HTTP 302 response
	Headers302 *DownloadDatabaseV2Response302Headers
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DownloadDatabaseV2Response) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DownloadDatabaseV2Response) GetJSON401() *V2Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DownloadDatabaseV2Response) GetJSON403() *V2NotLicensed {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DownloadDatabaseV2Response) GetJSON404() *V2UnknownDatabase {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DownloadDatabaseV2Response) GetJSON503() *V2NotAvailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DownloadDatabaseV2Response) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DownloadDatabaseV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadDatabaseV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DownloadDatabaseV2Response) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDownloadsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Downloads []Download `json:"downloads"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *V2Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDownloadsResponse) GetJSON200() *struct {
	Downloads []Download `json:"downloads"`
} {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListDownloadsResponse) GetJSON401() *V2Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListDownloadsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDownloadsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDownloadsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDownloadsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDatabasesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Databases []Database `json:"databases"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *V2Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDatabasesResponse) GetJSON200() *struct {
	Databases []Database `json:"databases"`
} {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListDatabasesResponse) GetJSON401() *V2Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListDatabasesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDatabasesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDatabasesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDatabasesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatabaseMetadataV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DatabaseMetadata
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *V2Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *V2NotLicensed
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *V2UnknownDatabase
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *V2NotAvailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DatabaseMetadataV2Response) GetJSON200() *DatabaseMetadata {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DatabaseMetadataV2Response) GetJSON401() *V2Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DatabaseMetadataV2Response) GetJSON403() *V2NotLicensed {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DatabaseMetadataV2Response) GetJSON404() *V2UnknownDatabase {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DatabaseMetadataV2Response) GetJSON503() *V2NotAvailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DatabaseMetadataV2Response) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DatabaseMetadataV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatabaseMetadataV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatabaseMetadataV2Response) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DatabaseChecksumV2WithResponse Checksums
//
// Checksums for one published file, so a download can be verified after it lands.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v2/database/checksum (the `DatabaseChecksumV2` operationId).
func (c *ClientWithResponses) DatabaseChecksumV2WithResponse(ctx context.Context, params *DatabaseChecksumV2Params, reqEditors ...RequestEditorFn) (*DatabaseChecksumV2Response, error) {
	rsp, err := c.DatabaseChecksumV2(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatabaseChecksumV2Response(rsp)
}

// DownloadDatabaseV2WithResponse Download
//
// Answers `302`; the bytes come straight from object storage rather than
// through this API. Follow the redirect.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v2/database/download (the `DownloadDatabaseV2` operationId).
func (c *ClientWithResponses) DownloadDatabaseV2WithResponse(ctx context.Context, params *DownloadDatabaseV2Params, reqEditors ...RequestEditorFn) (*DownloadDatabaseV2Response, error) {
	rsp, err := c.DownloadDatabaseV2(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadDatabaseV2Response(rsp)
}

// ListDownloadsWithResponse History
//
// Refusals are listed too: a denial is what answers "it stopped working",
// and its absence answers nothing.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v2/database/downloads (the `ListDownloads` operationId).
func (c *ClientWithResponses) ListDownloadsWithResponse(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*ListDownloadsResponse, error) {
	rsp, err := c.ListDownloads(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDownloadsResponse(rsp)
}

// ListDatabasesWithResponse List
//
// The whole published catalog, with your organization's licence beside
// each entry, so `standing` says whether a database is yours today
// (`licensed`), was (`expired`), or has never been bought (`unlicensed`).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v2/database/list (the `ListDatabases` operationId).
func (c *ClientWithResponses) ListDatabasesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDatabasesResponse, error) {
	rsp, err := c.ListDatabases(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDatabasesResponse(rsp)
}

// DatabaseMetadataV2WithResponse Metadata
//
// Poll this to decide whether today's build is worth fetching: it carries
// `updated` and `entries` without downloading anything.
//
// No `format` parameter - one document describes every format the database
// is built in.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v2/database/metadata (the `DatabaseMetadataV2` operationId).
func (c *ClientWithResponses) DatabaseMetadataV2WithResponse(ctx context.Context, params *DatabaseMetadataV2Params, reqEditors ...RequestEditorFn) (*DatabaseMetadataV2Response, error) {
	rsp, err := c.DatabaseMetadataV2(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatabaseMetadataV2Response(rsp)
}

// ParseDatabaseChecksumV2Response parses an HTTP response from a DatabaseChecksumV2WithResponse call
func ParseDatabaseChecksumV2Response(rsp *http.Response) (*DatabaseChecksumV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatabaseChecksumV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Checksums DBChecksums                                 `json:"checksums"`
			Format    DatabaseChecksumV2200JSONResponseBodyFormat `json:"format"`
			ID        string                                      `json:"id"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest V2Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest V2NotLicensed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest V2UnknownDatabase
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest V2NotAvailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDownloadDatabaseV2Response parses an HTTP response from a DownloadDatabaseV2WithResponse call
func ParseDownloadDatabaseV2Response(rsp *http.Response) (*DownloadDatabaseV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadDatabaseV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 302:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest V2Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest V2NotLicensed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest V2UnknownDatabase
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest V2NotAvailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 302:
		var headers DownloadDatabaseV2Response302Headers
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		response.Headers302 = &headers
	}

	return response, nil
}

// ParseListDownloadsResponse parses an HTTP response from a ListDownloadsWithResponse call
func ParseListDownloadsResponse(rsp *http.Response) (*ListDownloadsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDownloadsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Downloads []Download `json:"downloads"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest V2Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListDatabasesResponse parses an HTTP response from a ListDatabasesWithResponse call
func ParseListDatabasesResponse(rsp *http.Response) (*ListDatabasesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDatabasesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Databases []Database `json:"databases"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest V2Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseDatabaseMetadataV2Response parses an HTTP response from a DatabaseMetadataV2WithResponse call
func ParseDatabaseMetadataV2Response(rsp *http.Response) (*DatabaseMetadataV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatabaseMetadataV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DatabaseMetadata
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest V2Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest V2NotLicensed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest V2UnknownDatabase
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest V2NotAvailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
